FrontEnd/Models/CompraViewModel.cs
using BackEnd.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FrontEnd.Models
{
    public class CompraViewModel
    {
 
        public string sala { get; set; }

        public List<string>numero_asiento {get;set;}

        public string cantidad_asientos { get; set; }

        public string precio_entradas { get; set; }

    }
}

FrontEnd/Models/ProyeccionesViewModel.cs
using BackEnd.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FrontEnd.Models
{
    public class ProyeccionesViewModel
    {
        public int id_proyeccion { get; set; }
        public Nullable<int> id_sala { get; set; }
        public Nullable<int> id_pelicula { get; set; }
        public Nullable<int> id_formato { get; set; }
        public string hora { get; set; }

       

        public virtual Formato Formato { get; set; }
        public virtual Pelicula Pelicula { get; set; }
        public virtual Sala Sala { get; set; }
        public virtual Clasificacion Clasificacion { get; set; }
        
        public List <Asiento> asientos { get; set; }

    }
}

FrontEnd/Controllers/ComidasController.cs
using BackEnd.DAL;
using BackEnd.Entities;
using FrontEnd.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace FrontEnd.Controllers
{
    [Authorize(Roles = "Administrador,Consulta")]
    public class ComidasController : Controller
    {
        // GET: Comidas
        public ActionResult Index()
        {

            List<Producto> proyecciones;

            using (UnidadDeTrabajo<Producto> unidad = new UnidadDeTrabajo<Producto>(new BDContext()))
            {
                proyecciones = unidad.genericDAL.GetAll().ToList();
            }


            List<ComidasViewModel> proyeccionesVM = new List<ComidasViewModel>();

            ComidasViewModel proyeccionesViewModel;
            foreach (var item in proyecciones)
            {

                proyeccionesViewModel = new ComidasViewModel
                {
                    id_comida = item.id_comida,
                    cantidad = item.cantidad,
                    nombre = item.nombre,
                    precio = item.precio,
                    imagen_comida = item.imagen_comida
                };
                proyeccionesVM.Add(proyeccionesViewModel);
            }



            return View(proyeccionesVM);
        }

        public ActionResult Create()
        {
            ComidasViewModel comidas = new ComidasViewModel();
            return View(comidas);
        }
        [Authorize(Roles = "Administrador")]
        [HttpPost]
        public ActionResult Create(ComidasViewModel comidasViewModel)
        {
            string mensaje = "";
            try
            {
                mensaje = "Agregado con exito";


                Producto produc = new Producto()
                {

                    nombre = comidasViewModel.nombre,
                    precio = comidasViewModel.precio,
                    cantidad = comidasViewModel.cantidad,
                    imagen_comida = comidasViewModel.imagen_comida
                };

                using (UnidadDeTrabajo<Producto> unidad = new UnidadDeTrabajo<Producto>(new BDContext()))
                {
                    produc.id_comida = unidad.genericDAL.GetAll().Count() + 1;

                    unidad.genericDAL.Add(produc);
                    unidad.Complete();
                }
            }
            catch (Exception ex)
            {
                mensaje = ex.ToString();
            }
            TempData["mensaje"] = mensaje;
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            ComidasViewModel comidasViewModel;
            Producto producto;
            using (UnidadDeTrabajo<Producto> unidad = new UnidadDeTrabajo<Producto>(new BDContext()))
            {
                producto = unidad.genericDAL.Get(id);
            }
            comidasViewModel = new ComidasViewModel()
            {
                id_comida = producto.id_comida,
                nombre = producto.nombre,
                precio = producto.precio,
                cantidad = producto.cantidad,
                imagen_comida = producto.imagen_comida

            };
            return View(comidasViewModel);
        }

        [HttpPost]
        public ActionResult Edit(ComidasViewModel comidasViewModel)
        {
            string mensaje = "";
            try
            {
                mensaje = "Modificado con exito";
                Producto producto = new Producto()
                {
                    id_comida = comidasViewModel.id_comida,
                    nombre = comidasViewModel.nombre,
                    precio = comidasViewModel.precio,
                    cantidad = comidasViewModel.cantidad,
                    imagen_comida = comidasViewModel.imagen_comida

                };

                using (UnidadDeTrabajo<Producto> unidad = new UnidadDeTrabajo<Producto>(new BDContext()))
                {
                    unidad.genericDAL.Update(producto);
                    unidad.Complete();
                }
            }
            catch (Exception ex)
            {
                mensaje = ex.ToString();
            }
            TempData["mensaje"] = mensaje;
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            string mensaje = "";
            try
            {
                mensaje = "Eliminado con exito";
                Producto producto;
                using (UnidadDeTrabajo<Producto> unidad = new UnidadDeTrabajo<Producto>(new BDContext()))
                {
                    producto = unidad.genericDAL.Get(id);
                    unidad.genericDAL.Remove(producto);
                    unidad.Complete();
                }
            }
            catch (Exception ex)
            {
                mensaje = ex.ToString();
            }
            TempData["mensaje"] = mensaje;
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            ComidasViewModel comidasViewModel;
            Producto producto;

            using (UnidadDeTrabajo<Producto> unidad = new UnidadDeTrabajo<Producto>(new BDContext()))
            {
                producto = unidad.genericDAL.Get(id);
            }
            comidasViewModel = new ComidasViewModel()
            {
                id_comida = producto.id_comida,
                nombre = producto.nombre,
                precio = producto.precio,
                cantidad = producto.cantidad
            };
            return View(comidasViewModel);
        }

        [HttpPost]
        public JsonResult Datos_Usuario(User user)
        {
            Session["Usuario_Compra"] = user;

            if (user != null)
                return Json("'Success':'true'" + user);
            else
                return Json(String.Format("'Success':'false','Error':'Ha habido un error al mapear los datos.'"));
        }

        [HttpPost]
        public JsonResult Compra_Final(ProductoViewModel producto)
        {
            IUserDAL userDAL = new UserDALImpl();
            CompraViewModel lista = Session["Entradas"] as CompraViewModel;
            User userViewModel = Session["Usuario_Compra"] as User;
            Session["Orden_Comida"] = producto;
            producto = Session["Orden_Comida"] as ProductoViewModel;
            int id_sala = Convert.ToInt32(lista.sala);
            Asiento asiento = new Asiento();
            Reserva reserva = new Reserva();
            User user_temp;
            User user = new User()

            {
                nombre = userViewModel.nombre,
                apellidos = userViewModel.apellidos,
                Password = userViewModel.Password,
                mail = userViewModel.mail,
                UserName = userViewModel.nombre,
                phone = userViewModel.phone,
                card = userViewModel.card

            };



            using (UnidadDeTrabajo<User> unidad = new UnidadDeTrabajo<User>(new BDContext()))
            {

                unidad.genericDAL.Add(user);
                unidad.Complete();
                user_temp = userDAL.getUser(user.nombre);
                reserva.id_cliente = user_temp.UserId;

            }

            foreach (var item in lista.numero_asiento)
            {
                asiento.id_sala = id_sala;
                asiento.numero_asiento = item;
                asiento.estado = 1;
                using (UnidadDeTrabajo<Asiento> unidad = new UnidadDeTrabajo<Asiento>(new BDContext()))
                {
                    asiento.id_asiento = unidad.genericDAL.GetAll().Count() + 1;
                    unidad.genericDAL.Add(asiento);
                    unidad.Complete();
                    reserva.id_asiento = unidad.genericDAL.GetAll().Count();
                }

                using (UnidadDeTrabajo<Reserva> unidad = new UnidadDeTrabajo<Reserva>(new BDContext()))
                {
                    reserva.id_reserva = unidad.genericDAL.GetAll().Count() + 1;
                    unidad.genericDAL.Add(reserva);
                    unidad.Complete();
                }
            }

            return Json("Exito");
        }

        public ActionResult About()
        {


            return Redirect("~/Reports/Factura.aspx");
        }
    }
}
  

FrontEnd/Controllers/ProyeccionesController.cs
using BackEnd.DAL;
using BackEnd.Entities;
using FrontEnd.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FrontEnd.Controllers
{
    [Authorize(Roles = "Administrador,Consulta")]
    public class ProyeccionesController : Controller
    {
        // GET: Peliculas
        public ActionResult Index()
        {
            List<Proyeccione> proyecciones;
           
            Pelicula pelicula;
            using (UnidadDeTrabajo<Proyeccione> unidad = new UnidadDeTrabajo<Proyeccione>(new BDContext()))
            {
                proyecciones = unidad.genericDAL.GetAll().ToList();
            }


            List<ProyeccionesViewModel> proyeccionesVM = new List<ProyeccionesViewModel>();

            ProyeccionesViewModel proyeccionesViewModel;
            foreach (var item in proyecciones)
            {
                using (UnidadDeTrabajo<Pelicula> unidad = new UnidadDeTrabajo<Pelicula>(new BDContext()))
                {
                    pelicula = unidad.genericDAL.Get(item.id_pelicula);
                }
                proyeccionesViewModel = new ProyeccionesViewModel
                {
                    id_formato = item.id_formato,
                    hora = item.hora,
                    id_pelicula = item.id_pelicula,
                    id_proyeccion = item.id_proyeccion,
                    id_sala = item.id_sala,
                    Pelicula = pelicula
                };
                proyeccionesVM.Add(proyeccionesViewModel);
            }
            return View(proyeccionesVM);
        }

        public ActionResult Detalles(int id)
        {
            IAsientoDAL asientoDAL = new AsientoDALImpl();
            Proyeccione proyeccione;
            Sala sala;
            Pelicula pelicula;
            Clasificacion clasificacion;
            Formato formato;
            List<Asiento> reservados;
            using (UnidadDeTrabajo<Proyeccione> unidad = new UnidadDeTrabajo<Proyeccione>(new BDContext()))
            {
                proyeccione = unidad.genericDAL.Get(id);

            }
            using (UnidadDeTrabajo<Sala> unidad = new UnidadDeTrabajo<Sala>(new BDContext()))
            {
                sala = unidad.genericDAL.Get(proyeccione.id_sala);

            }

            using (UnidadDeTrabajo<Pelicula> unidad = new UnidadDeTrabajo<Pelicula>(new BDContext()))
            {
                pelicula = unidad.genericDAL.Get(proyeccione.id_pelicula);

            }
            using (UnidadDeTrabajo<Clasificacion> unidad = new UnidadDeTrabajo<Clasificacion>(new BDContext()))
            {
                clasificacion = unidad.genericDAL.Get(pelicula.id_clasifacion);

            }
            using (UnidadDeTrabajo<Formato> unidad = new UnidadDeTrabajo<Formato>(new BDContext()))
            {
                formato = unidad.genericDAL.Get(proyeccione.id_formato);

            }
            using (UnidadDeTrabajo<Formato> unidad = new UnidadDeTrabajo<Formato>(new BDContext()))
            {
                reservados = asientoDAL.GetAsientosId(proyeccione.id_sala);
            }
            ProyeccionesViewModel proyeccionesViewModel;


            proyeccionesViewModel = new ProyeccionesViewModel
            {
                id_formato = proyeccione.id_formato,
                id_pelicula = proyeccione.id_pelicula,
                hora = proyeccione.hora,
                id_proyeccion = proyeccione.id_proyeccion,
                id_sala = proyeccione.id_sala,
                Sala = sala,
                Pelicula = pelicula,
                Clasificacion = clasificacion,
                Formato = formato,
                asientos = reservados


        };

            return View(proyeccionesViewModel);
        }


        [HttpPost]
        public JsonResult Entradas(CompraViewModel data)
        {
            
           
            Session["Entradas"] = data;
            
            if (data!= null)
                return Json("'Success':'true'"+data);
            else
                return Json(String.Format("'Success':'false','Error':'Ha habido un error al mapear los datos.'"));
        }

        public JsonResult ConsultaReservas(string[] data)
        {
            
            if (data != null)
            {
                int data1 = int.Parse(data[0]);
                List<AsientoViewModel> asientos_ocupados= new List<AsientoViewModel>();
                AsientoViewModel asiento;
                List<Asiento> lista;
                using (BDContext context = new BDContext())
                {
                    lista = (from c in context.Asientoes
                             where c.id_sala == data1
                             select c).ToList();

                }
                foreach (var item in lista)
                {
                    asiento = new AsientoViewModel {

                    id_asiento = item.id_asiento,
                    id_sala = item.id_sala,
                    numero_asiento = item.numero_asiento,
                    estado = item.estado
                };
                    
                    asientos_ocupados.Add(asiento);
                }
               
                return Json(asientos_ocupados);
            }
            else 
                return Json(String.Format("'Success':'false','Error':'Ha habido un error al mapear los datos.'"));
        }

        public ActionResult Compra() {

            UserViewModel user = new UserViewModel();
           
            return View(user);
        }

        [HttpPost]
        public ActionResult Compra(UserViewModel userViewModel)
        {
            
            CompraViewModel lista= Session["Entradas"] as CompraViewModel;
            
            IUserDAL userDAL = new UserDALImpl();
            User user_temp;
            int id_sala = Convert.ToInt32(lista.sala);
            Asiento asiento = new Asiento();
            Reserva reserva = new Reserva();
            User user = new User()
            {
                
                nombre = userViewModel.nombre,
                apellidos = userViewModel.apellidos,
                Password = userViewModel.Password,
                mail = userViewModel.mail,
                UserName = userViewModel.nombre,
                phone = userViewModel.phone,
                card= userViewModel.card
                
            };

            Session["Usuario_Compra"] = user;

            using (UnidadDeTrabajo<User> unidad = new UnidadDeTrabajo<User>(new BDContext()))
            {
                
                unidad.genericDAL.Add(user);
                unidad.Complete();
                user_temp = userDAL.getUser(user.nombre);
                reserva.id_cliente = user_temp.UserId;

            }

            foreach (var item in lista.numero_asiento)
            {
                asiento.id_sala = id_sala;
                asiento.numero_asiento = item;
                asiento.estado = 1;
                using (UnidadDeTrabajo<Asiento> unidad = new UnidadDeTrabajo<Asiento>(new BDContext()))
                {
                    asiento.id_asiento = unidad.genericDAL.GetAll().Count() + 1;
                    unidad.genericDAL.Add(asiento);
                    unidad.Complete();
                    reserva.id_asiento = unidad.genericDAL.GetAll().Count();
                }

                using (UnidadDeTrabajo<Reserva> unidad = new UnidadDeTrabajo<Reserva>(new BDContext()))
                {
                    reserva.id_reserva = unidad.genericDAL.GetAll().Count()+1;
                    unidad.genericDAL.Add(reserva);
                    unidad.Complete();
                }
            }

           
            return RedirectToAction("About", "Proyecciones");

        }

        public ActionResult About()
        {


            return Redirect("~/Reports/Factura.aspx");
        }

    }
    }

FrontEnd/Views/Proyecciones/Compra (2).cshtml
@model FrontEnd.Models.UserViewModel

@{
    ViewBag.Title = "Compra";
}

<h2>Compra</h2>

<script type="text/javascript">

    var usuario = {
        UserName: "",
        nombre: "",
        Password: "",
        mail: "",
        phone: "",
        apellidos: "",
        card: ""
    };
    var urlComprar ='@Url.Action("Datos_Usuario", "Comidas")';


    $(document).ready(function () {
          
        $("#si").click(function () {
            usuario.UserName = $(".nombre").val();
            usuario.apellidos = $(".apellidos").val();
            usuario.nombre = $(".nombre").val();
            usuario.Password = "";
            usuario.phone = $(".phone").val();
            usuario.card = $(".card").val();
            usuario.mail = $(".mail").val();
           
              $.ajax({
               url: urlComprar,
               data: JSON.stringify(usuario),
               type: 'POST',
               dataType:"json",
               contentType: 'application/json',
                 success: function (response)
                 {
                   alert("Datos enviados" + response); 
                  
                   location.href = '@Url.Action("Index","Comidas")';
                 }, error: function (response) {
                   
                   console.log("Error" + response);
                 } 

            });

           
        });

       
    });


   

</script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control nombre" } })
            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.mail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.mail, new { htmlAttributes = new { @class = "form-control mail" } })
            @Html.ValidationMessageFor(model => model.mail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control phone" } })
            @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.apellidos, new { htmlAttributes = new { @class = "form-control apellidos" } })
            @Html.ValidationMessageFor(model => model.apellidos, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.tarjeta, htmlAttributes: new { @class = "control-label col-md-2 " })
        <div class="col-md-10">
            @Html.EditorFor(model => model.tarjeta, new { htmlAttributes = new { @class = "form-control card" } })
            @Html.ValidationMessageFor(model => model.tarjeta, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <text class="control-label col-md-2">Fecha de expiracion</text>
    </div>
    <div class="form-group float-left">


        <select class="custom-select" required>
            <option value="">0</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
            <option value="7">7</option>
            <option value="8">8</option>
            <option value="9">9</option>
            <option value="10">10</option>
            <option value="11">11</option>
            <option value="12">12</option>
        </select>


    </div>

    <div class="form-group">
        <select class="custom-select" required>
            <option value="">Seleccione un año</option>
            <option value="1">2020</option>
            <option value="2">2021</option>
            <option value="3">2022</option>
            <option value="4">2023</option>
            <option value="5">2024</option>
            <option value="6">2025</option>
            <option value="8">2026</option>
            <option value="9">2027</option>
            <option value="10">2028</option>
            <option value="11">2029</option>
            <option value="12">2030</option>
            <option value="13">2031</option>
        </select>

    </div>
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
       Finalizar Compra
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Desea agregar una comida</h5>
                </div>
              
                <div class="modal-footer">
                    <button type="submit" id="no" value="false" class="btn btn-secondary">No</button>
                    <button type="button" id="si" value="true" class="btn btn-primary">Si</button>
                </div>
            </div>
        </div>
    </div>
    </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

FrontEnd/Views/Proyecciones/Compra.cshtml
@model FrontEnd.Models.UserViewModel

@{
    ViewBag.Title = "Compra";
}

<h2>Compra</h2>

<script type="text/javascript">

    var usuario = {
        UserName: "",
        nombre: "",
        Password: "",
        mail: "",
        phone: "",
        apellidos: "",
        card: ""
    };
    var urlComprar ='@Url.Action("Datos_Usuario", "Comidas")';


    $(document).ready(function () {
          
        $("#si").click(function () {
            usuario.UserName = $(".nombre").val();
            usuario.apellidos = $(".apellidos").val();
            usuario.nombre = $(".nombre").val();
            usuario.Password = "";
            usuario.phone = $(".phone").val();
            usuario.card = $(".card").val();
            usuario.mail = $(".mail").val();
           
              $.ajax({
               url: urlComprar,
               data: JSON.stringify(usuario),
               type: 'POST',
               dataType:"json",
               contentType: 'application/json',
                 success: function (response)
                 {
                   alert("Datos enviados" + response); 
                  
                   location.href = '@Url.Action("Index","Comidas")';
                 }, error: function (response) {
                   
                   console.log("Error" + response);
                 } 

            });

           
        });

       
    });


   

</script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control nombre" } })
            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.mail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.mail, new { htmlAttributes = new { @class = "form-control mail" } })
            @Html.ValidationMessageFor(model => model.mail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control phone" } })
            @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.apellidos, new { htmlAttributes = new { @class = "form-control apellidos" } })
            @Html.ValidationMessageFor(model => model.apellidos, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.card, htmlAttributes: new { @class = "control-label col-md-2 " })
        <div class="col-md-10">
            @Html.EditorFor(model => model.card, new { htmlAttributes = new { @class = "form-control card" } })
            @Html.ValidationMessageFor(model => model.card, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <text class="control-label col-md-2">Fecha de expiracion</text>
    </div>
    <div class="form-group float-left">


        <select class="custom-select" required>
            <option value="">0</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
            <option value="7">7</option>
            <option value="8">8</option>
            <option value="9">9</option>
            <option value="10">10</option>
            <option value="11">11</option>
            <option value="12">12</option>
        </select>


    </div>

    <div class="form-group">
        <select class="custom-select" required>
            <option value="">Seleccione un año</option>
            <option value="1">2020</option>
            <option value="2">2021</option>
            <option value="3">2022</option>
            <option value="4">2023</option>
            <option value="5">2024</option>
            <option value="6">2025</option>
            <option value="8">2026</option>
            <option value="9">2027</option>
            <option value="10">2028</option>
            <option value="11">2029</option>
            <option value="12">2030</option>
            <option value="13">2031</option>
        </select>

    </div>
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
       Finalizar Compra
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Desea agregar una comida</h5>
                </div>
              
                <div class="modal-footer">
                    <button type="submit" id="no" value="false" class="btn btn-secondary">No</button>
                    <button type="button" id="si" value="true" class="btn btn-primary">Si</button>
                </div>
            </div>
        </div>
    </div>
    </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

FrontEnd/Views/Proyecciones/Delete.cshtml
@model FrontEnd.Models.ProyeccionesViewModel

@{
    ViewBag.Title = "View1";
}

<h2>View1</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProyeccionesViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.id_proyeccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_proyeccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.id_sala)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_sala)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.id_pelicula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_pelicula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hora)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hora)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>