FrontEnd/Models/PeliculaViewModel.cs
using BackEnd.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FrontEnd.Models
{
    public class PeliculaViewModel
    {

        public int id_pelicula { get; set; }
        public int id_clasifacion { get; set; }
        public string nombre_pelicula { get; set; }
        public string duracion_pelicula { get; set; }
        public int id_genero { get; set; }
        public string imagen_pelicula { get; set; }
        public int id_formato { get; set; }

        public virtual Clasificacion Clasificacion { get; set; }
        public virtual Formato Formato { get; set; }
        public virtual Genero Genero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proyeccion> Proyeccion { get; set; }
    }
}

FrontEnd/Controllers/PeliculasController.cs
using BackEnd.DAL;
using BackEnd.Entities;
using FrontEnd.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FrontEnd.Controllers
{
    public class PeliculasController : Controller
    {
        // GET: Peliculas
        public ActionResult Index()
        {
            PeliculaViewModel peliculaViewModel;
            string mensaje = "";
            if (TempData["mensaje"] != null)
            {
                mensaje = TempData["mensaje"].ToString();
            }

            List<Pelicula> pelicula;
            PeliculaDALImpl peliculaDAL = new PeliculaDALImpl();

            pelicula = peliculaDAL.GetPeliculas();

            List<PeliculaViewModel> peliculaVM = new List<PeliculaViewModel>();

            PeliculaViewModel PeliculaViewModel;
            foreach (var item in pelicula)
            {
                peliculaViewModel = new PeliculaViewModel
                {
                     id_pelicula = item.id_pelicula,
                     id_clasifacion = item.id_clasifacion,
                     id_formato = item.id_formato,
                     id_genero = item.id_genero,
                     nombre_pelicula = item.nombre_pelicula,
                     imagen_pelicula = item.imagen_pelicula
                };
                peliculaVM.Add(peliculaViewModel);
            }
            return View(peliculaVM);
        }

        public ActionResult Create()
        {
            PeliculaViewModel pelicula = new PeliculaViewModel();
            return View(pelicula);
        }

        [HttpPost]
        public ActionResult Create(PeliculaViewModel peliculaViewModel)
        {
            PeliculaDALImpl peliculaDAL = new PeliculaDALImpl();
            string mensaje = "";
            try
            {
                mensaje = "Agregado con exito";
                Pelicula pelicula = new Pelicula()
                {
                    id_pelicula = peliculaDAL.GetPeliculas().Count + 1, 
                    id_clasifacion = peliculaViewModel.id_clasifacion,
                    id_formato = peliculaViewModel.id_formato,
                    id_genero= peliculaViewModel.id_genero,
                    nombre_pelicula = peliculaViewModel.nombre_pelicula,
                    imagen_pelicula = peliculaViewModel.imagen_pelicula,
                    duracion_pelicula = peliculaViewModel.duracion_pelicula
                };

                peliculaDAL.AddPelicula(pelicula);
            }
            catch (Exception ex)
            {
                mensaje = ex.ToString();
            }
            TempData["mensaje"] = mensaje;
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            PeliculaDALImpl peliculaDAL = new PeliculaDALImpl();

            PeliculaViewModel peliculaViewModel;

            Pelicula pelicula;

            pelicula = peliculaDAL.GetPeliculaById(id);


            peliculaViewModel = new PeliculaViewModel()
            {
                
                id_pelicula = pelicula.id_pelicula,
                id_clasifacion = pelicula.id_clasifacion,
                id_formato = pelicula.id_formato,
                id_genero = pelicula.id_genero,
                nombre_pelicula = pelicula.nombre_pelicula,
                imagen_pelicula = pelicula.imagen_pelicula,
                duracion_pelicula = pelicula.duracion_pelicula

            };
            return View(peliculaViewModel);
        }

        public JsonResult ConsultaFormato(string[] data)
        {
            FormatoDALImpl formatoDAL = new FormatoDALImpl();
            Formato formato_temporal;

            FormatoViewModel formatoViewModel;
            if (data != null)
            {
                int data1 = int.Parse(data[0]);

               formato_temporal = formatoDAL.GetFormatoById(data1);


                formatoViewModel = new FormatoViewModel
                {

                     id_formato = formato_temporal.id_formato,
                     formato1 = formato_temporal.formato1



                };

                return Json(formatoViewModel);
            }
            else
                return Json(String.Format("'Success':'false','Error':'Ha habido un error al mapear los datos.'"));
        }

        public JsonResult ConsultaClasificacion(string[] data)
        {
            ClasificacionDALImpl clasificacionDAL = new ClasificacionDALImpl();
            Clasificacion clasificacion_temporal;

            ClasificacionViewModel clasificacionViewModel;
            if (data != null)
            {
                int data1 = int.Parse(data[0]);

                clasificacion_temporal = clasificacionDAL.GetClasificacionById(data1);


                clasificacionViewModel = new ClasificacionViewModel
                {

                     id_clasificacion = clasificacion_temporal.id_clasificacion,
                     tipo_clasificacion = clasificacion_temporal.tipo_clasificacion



                };

                return Json(clasificacionViewModel);
            }
            else
                return Json(String.Format("'Success':'false','Error':'Ha habido un error al mapear los datos.'"));
        }

        public JsonResult ConsultaGenero(string[] data)
        {
            GeneroDALImpl generoDAL = new GeneroDALImpl();
            Genero genero_temporal;

            GeneroViewModel generoViewModel;
            if (data != null)
            {
                int data1 = int.Parse(data[0]);

                genero_temporal = generoDAL.GetGeneroById(data1);


                generoViewModel = new GeneroViewModel
                {

                    
                     id_genero = genero_temporal.id_genero,
                     genero1 = genero_temporal.genero1


                };

                return Json(generoViewModel);
            }
            else
                return Json(String.Format("'Success':'false','Error':'Ha habido un error al mapear los datos.'"));
        }

        [HttpPost]
        public ActionResult Edit(PeliculaViewModel peliculaViewModel)
        {
            PeliculaDALImpl peliculaDAL = new PeliculaDALImpl();
            string mensaje = "";
            try
            {
                mensaje = "Modificado con exito";
                Pelicula pelicula = new Pelicula()
                {
                    id_pelicula= peliculaViewModel.id_pelicula,
                    id_clasifacion = peliculaViewModel.id_clasifacion,
                    id_formato = peliculaViewModel.id_formato,
                    id_genero = peliculaViewModel.id_genero,
                    nombre_pelicula = peliculaViewModel.nombre_pelicula,
                    imagen_pelicula = peliculaViewModel.imagen_pelicula,
                    duracion_pelicula = peliculaViewModel.duracion_pelicula

                };

                peliculaDAL.UpdatePelicula(pelicula);
            }
            catch (Exception ex)
            {
                mensaje = ex.ToString();
            }
            TempData["mensaje"] = mensaje;
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            PeliculaDALImpl peliculaDAL = new PeliculaDALImpl();
            string mensaje = "";
            try
            {
                mensaje = "Eliminado con exito";
                Pelicula pelicula;

                pelicula = peliculaDAL.GetPeliculaById(id);
                peliculaDAL.DeletePelicula(pelicula.id_pelicula);


            }
            catch (Exception ex)
            {
                mensaje = ex.ToString();
            }
            TempData["mensaje"] = mensaje;
            return RedirectToAction("Index");
        }

        
    }
}
    

FrontEnd/Views/Peliculas/Create.cshtml
@model FrontEnd.Models.PeliculaViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<script>


    var clasificacion = [];
    var formato = [];
    var genero = [];
    var temporal1;
    var temporal2;
    var temporal3;
    var clasifiactionName;
    var formatoName;
    var generoName;
    var urlClasificacion = '@Url.Action("ConsultaClasificacion", "Peliculas")';
    var urlGenero = '@Url.Action("ConsultaGenero", "Peliculas")';
    var urlFormato = '@Url.Action("ConsultaFormato", "Peliculas")';

    $(document).ready(function () {

        clasificacion();
        genero();
        formato();
  function clasificacion () {
    $(".id_clasificacion").click(function () {
    clasificacion = [$(".id_clasificacion").val()]
    $.ajax({
    url: urlClasificacion,
    data: JSON.stringify(clasificacion),
    type: 'POST',
    dataType: "json",
    contentType: 'application/json',
    success: function (response) {



    temporal1 = JSON.stringify(response);
    clasificacionName = JSON.parse(temporal1);
    $("#clasificacion_name").val(clasificacionName.tipo_clasificacion);
    console.log("ID Clasificacion" + clasificacion);

    }, error: function (response) {

    console.log("Error" + response);
    }

    });

    });
    }

    function formato() {
    $(".id_formato").click(function () {
    formato = [$(".id_formato").val()]
    $.ajax({
    url: urlFormato,
    data: JSON.stringify(formato),
    type: 'POST',
    dataType: "json",
    contentType: 'application/json',
    success: function (response) {



    temporal2 = JSON.stringify(response);
    formatoName = JSON.parse(temporal2);
    $("#formato_name").val(formatoName.formato1);
    console.log("ID FORMATO" + formatoName);

    }, error: function (response) {

    console.log("Error" + response);
    }

    });

    });
    }

    function genero() {
    $(".id_genero").click(function () {
    genero = [$(".id_genero").val()]
    $.ajax({
    url: urlGenero,
    data: JSON.stringify(genero),
    type: 'POST',
    dataType: "json",
    contentType: 'application/json',
    success: function (response) {



    temporal3 = JSON.stringify(response);
    generoName = JSON.parse(temporal3);
    $("#genero_name").val(generoName.genero1);
    console.log("ID GENERO" + generoName);

    }, error: function (response) {

    console.log("Error" + response);
    }

    });

    });
    }
    });
    </script>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>PeliculaViewModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.id_clasifacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_clasifacion, new { htmlAttributes = new { @class = "form-control id_clasificacion" } })
                @Html.ValidationMessageFor(model => model.id_clasifacion, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-offset-2 col-md-10">
                <input id="clasificacion_name" disabled />
            </div>
        </div>

            <div class="form-group">
                @Html.LabelFor(model => model.nombre_pelicula, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nombre_pelicula, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nombre_pelicula, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.duracion_pelicula, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.duracion_pelicula, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.duracion_pelicula, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.id_genero, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.id_genero, new { htmlAttributes = new { @class = "form-control id_genero" } })
                    @Html.ValidationMessageFor(model => model.id_genero, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-offset-2 col-md-10">
                    <input id="genero_name" disabled />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.imagen_pelicula, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.imagen_pelicula, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.imagen_pelicula, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.id_formato, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.id_formato, new { htmlAttributes = new { @class = "form-control id_formato" } })
                    @Html.ValidationMessageFor(model => model.id_formato, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-offset-2 col-md-10">
                    <input id="formato_name" disabled />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

FrontEnd/Views/Peliculas/Delete.cshtml
@model FrontEnd.Models.PeliculaViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PeliculaViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.id_pelicula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_pelicula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.id_clasifacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_clasifacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre_pelicula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre_pelicula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.duracion_pelicula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.duracion_pelicula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.id_genero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_genero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imagen_pelicula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imagen_pelicula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.id_formato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_formato)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FrontEnd/Views/Peliculas/Edit.cshtml
@model FrontEnd.Models.PeliculaViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
<script>


    var clasificacion = [];
    var formato = [];
    var genero = [];
    var temporal1;
    var temporal2;
    var temporal3;
    var clasifiactionName;
    var formatoName;
    var generoName;
    var urlClasificacion = '@Url.Action("ConsultaClasificacion", "Peliculas")';
    var urlGenero = '@Url.Action("ConsultaGenero", "Peliculas")';
    var urlFormato = '@Url.Action("ConsultaFormato", "Peliculas")';

     $(document).ready(function () {

            clasificacion();
            genero();
            formato();

                clasificacion = [$(".id_clasificacion").val()];
                $.ajax({
                url: urlClasificacion,
                data: JSON.stringify(clasificacion),
                type: 'POST',
                dataType: "json",
                contentType: 'application/json',
                success: function (response) {



                    temporal1 = JSON.stringify(response);
                    clasificacionName = JSON.parse(temporal1);
                    $("#clasificacion_name").val(clasificacionName.tipo_clasificacion);
                    console.log("ID Clasificacion"+clasificacion);

                }, error: function (response) {

                    console.log("Error" + response);
                }

            });

        

         formato = [$(".id_formato").val()];
    $.ajax({
        url: urlFormato,
        data: JSON.stringify(formato),
        type: 'POST',
        dataType: "json",
        contentType: 'application/json',
        success: function (response) {



            temporal2 = JSON.stringify(response);
            formatoName = JSON.parse(temporal2);
            $("#formato_name").val(formatoName.formato1);
            console.log("ID FORMATO" + formatoName);

        }, error: function (response) {

            console.log("Error" + response);
        }

    });

         genero = [$(".id_genero").val()];
    $.ajax({
        url: urlGenero,
        data: JSON.stringify(genero),
        type: 'POST',
        dataType: "json",
        contentType: 'application/json',
        success: function (response) {



            temporal3 = JSON.stringify(response);
            generoName = JSON.parse(temporal3);
            $("#genero_name").val(generoName.genero1);
            console.log("ID GENERO" + generoName);

        }, error: function (response) {

            console.log("Error" + response);
        }

    });



        function clasificacion () {
            $(".id_clasificacion").click(function () {
                clasificacion = [$(".id_clasificacion").val()]
                $.ajax({
                    url: urlClasificacion,
                    data: JSON.stringify(clasificacion),
                    type: 'POST',
                    dataType: "json",
                    contentType: 'application/json',
                    success: function (response) {



                        temporal1 = JSON.stringify(response);
                        clasificacionName = JSON.parse(temporal1);
                        $("#clasificacion_name").val(clasificacionName.tipo_clasificacion);
                        console.log("ID Clasificacion" + clasificacion);

               }, error: function (response) {

                   console.log("Error" + response);
               }

            });

        });
    }

    function formato() {
        $(".id_formato").click(function () {
            formato = [$(".id_formato").val()]
            $.ajax({
                url: urlFormato,
                data: JSON.stringify(formato),
                type: 'POST',
                dataType: "json",
                contentType: 'application/json',
                success: function (response) {



                    temporal2 = JSON.stringify(response);
                    formatoName = JSON.parse(temporal2);
                    $("#formato_name").val(formatoName.formato1);
                    console.log("ID FORMATO" + formatoName);

                }, error: function (response) {

                    console.log("Error" + response);
                }

            });

        });
    }

    function genero() {
        $(".id_genero").click(function () {
            genero = [$(".id_genero").val()]
            $.ajax({
                url: urlGenero,
                data: JSON.stringify(genero),
                type: 'POST',
                dataType: "json",
                contentType: 'application/json',
                success: function (response) {



                    temporal3 = JSON.stringify(response);
                    generoName = JSON.parse(temporal3);
                    $("#genero_name").val(generoName.genero1);
                    console.log("ID GENERO" + generoName);

                }, error: function (response) {

                    console.log("Error" + response);
                }

                 });

               });
            }
     });
</script>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PeliculaViewModel</h4>
        <div class="form-group">
            @Html.LabelFor(model => model.id_pelicula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_pelicula, new { htmlAttributes = new { @class = "form-control disabled" } })
                @Html.ValidationMessageFor(model => model.id_pelicula, "", new { @class = "text-danger" })
            </div>
           
        </div>
      

        <div class="form-group">
            @Html.LabelFor(model => model.id_clasifacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_clasifacion, new { htmlAttributes = new { @class = "form-control id_clasificacion" } })
                @Html.ValidationMessageFor(model => model.id_clasifacion, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-offset-2 col-md-10">
                <input id="clasificacion_name" disabled />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre_pelicula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre_pelicula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre_pelicula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.duracion_pelicula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.duracion_pelicula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.duracion_pelicula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_genero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_genero, new { htmlAttributes = new { @class = "form-control id_genero" } })
                @Html.ValidationMessageFor(model => model.id_genero, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-offset-2 col-md-10">
                <input id="genero_name" disabled />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imagen_pelicula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imagen_pelicula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imagen_pelicula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_formato, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_formato, new { htmlAttributes = new { @class = "form-control id_formato" } })
                @Html.ValidationMessageFor(model => model.id_formato, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-offset-2 col-md-10">
                <input id="formato_name" disabled />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FrontEnd/Views/Peliculas/Index.cshtml
@model IEnumerable<FrontEnd.Models.PeliculaViewModel>

@{
    ViewBag.Title = "Index";
}
<p>

    <a href="@Url.Action("Create", "Peliculas")" class="btn btn-primary btn-sm">
        <ion-icon size="small" name="add"></ion-icon>
        <medium>Agregar</medium>
    </a>

</p>
<div class="container wow fadeInUp">
    <div class="row" id="portfolio-wrapper">
        @foreach (var item in Model)
        {
            <div class="col-lg-3  border bg-dark text-white">
                <img class="border mx-auto d-block " src="@item.imagen_pelicula" style="width:240px ;height:155px;">
                <div class="details text-center">

                    <h3 class="text-center text-white">@item.nombre_pelicula</h3>

                    <a href="@Url.Action("Edit", "Peliculas", new { id = item.id_pelicula})" class="btn btn-primary btn-sm ">
                        <p><small> <ion-icon class="border" size="small" name="create"></ion-icon> Editar</small></p>
                    </a>
                    <a href="@Url.Action("Delete", "Peliculas", new { id = item.id_pelicula})" class="btn btn-primary btn-sm">
                        <p><small> <ion-icon size="small" name="trash" class="border"></ion-icon> Eliminar</small></p>
                    </a>

                    <a href="@Url.Action("Details", "Peliculas", new { id = item.id_pelicula})" class="btn btn-primary btn-sm ">
                        <p><small><ion-icon class="border" size="small" name="list-box"></ion-icon> Detalles</small></p>
                    </a>

                </div>
            </div>
        }
    </div>
</div>